apiVersion: v1
kind: Service
metadata:
  name: {{ template "helloworld.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "helloworld.name" . }}
    chart: {{ template "helloworld.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.podport }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "helloworld.name" . }}
    release: {{ .Release.Name }}
